spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key_id=rzp_test_Sk7y3P0HIOOJbN
razorpay.key_secret=Yo51BGktJtk5GXr1xedlPgUs