spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

razorpay.key_id=rzp_test_Sk7y3P0HIOOJbN
razorpay.key_secret=Yo51BGktJtk5GXr1xedlPgUs

server.port=${PORT:8080}